name: RoSharp Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4

      - uses: actions/checkout@v4

      - name: Restore Packages
        run: nuget restore

      - name: Setup MSBuild.exe
        uses: microsoft/Setup-MSBuild@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Build
        run: | 
          msbuild RoSharp.csproj -t:rebuild -property:Configuration=Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RoSharp
          path: |
            ${{ github.workspace }}/bin/Release/net8.0/RoSharp.dll
            ${{ github.workspace }}/bin/Release/net8.0/RoSharp.xml
            ${{ github.workspace }}/bin/Release/*.nupkg